### ISSUE TITLE
Admin UI?

### ISSUE THREAD

**Issue by Riari** [AndreasElia/laravel-firefly#32]
I know this is more of a future discussion and unlikely to be an item for 1.0, but what's the plan for admin tools, if any?

I have mixed feelings about this as an admin panel is one of those things that will probably already exist in the host application. When I tackled this, I ended up compromising by including tools directly in the category/thread/post views, so they could be moved elsewhere or used as is - but I feel like that's an incomplete solution.

Moderation tools can (and probably should) be provided inline anyway, but maybe it would be worth providing very simple, basic admin views that can easily be overridden. Providing a REST API at least means the developer has the choice of implementing custom tools if they decide not to use the provided ones at all.

**Comment by NowNewStart** [comment]
Yeah I guess an API for that would be good, if the user is using an admin panel already, we should maybe make another package that can be easily integrated in existing admin panels? We should still deliver one, but maybe make it optional.

**Comment by AndreasElia** [comment]
I like the idea of including a very basic admin panel as well as a config boolean for enabling or disabling it (probably disabled by default?).

**Comment by Riari** [comment]
Sounds good.
