### ISSUE TITLE
Cannot create DIscussions

### ISSUE THREAD

**Issue by skino2019** [AndreasElia/laravel-firefly#38]
Im a complete noob so apologies if im missing something. 

ive just followed the instructions on pulling and getting firefly installed but cannot create discussions. 

error i get is. 

![issue](https://user-images.githubusercontent.com/49098035/112646106-161cc480-8e3f-11eb-9bc8-0c26047f0eed.jpg)

Is there any more documentation on getting it up and running correctly.

Cheers.

Super stoked that this has been picked up again :)

**Comment by AndreasElia** [comment]
Hey @skino2019, I'm very happy to hear you're stoked about this being picked up again. I've updated the readme to go over the setup of the user model for the `FireflyUser` trait.

If you have anymore problems, questions or feature requests, feel free to post them as issues. I'm yet to market this package as of yet, but if you have any feedback it would be greatly appreciated.
