### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by Arkitecht** [AndreasElia/laravel-firefly#43]
Hey, thanks very much for this package, looks to be a solid foundation to build off of.

I was wondering if you had any docs and / or roadmap plans?

I was thinking of using this in my project, but would like to add a concept of moderators where only certain users can create groups, and can moderate (remove / edit / censor) posts created by others. 

Do you have something like this in the works? 

I would be happy to give it a shot and contribute if not, but didn't want to duplicate the effort.

Thanks!

**Comment by Arkitecht** [comment]
Please disregard, I now see you are using Policies, and I can just override your policies with policies of my own.

If anything comes up you would like assistance on, please feel free to reach out, would be happy to help!

**Comment by AndreasElia** [comment]
Hey @Arkitecht, I hope you are well.

Sorry for the late reply, it has been a very busy day, but I'm glad you managed to sort this out 😄 

Take care!

**Comment by answeb** [comment]
Hi guys, how do you override the package policies ?
Thanks

**Comment by answeb** [comment]
I found how. To anybody who is looking for it :

-  Copy policies from vendor/andreaselia/laravel-firefly/src/Policies to your app/Policies
- Add in your app/AuthServiceProvider.php the following code

```
protected $policies = [
        Post::class => MyPostPolicy::class,
        Group::class => MyGroupPolicy::class,
        Discussion::class => MyDiscussionPolicy::class,
    ];
```

**Comment by andreaselia** [comment]
Thank you for sharing your solution so others may find it useful too 👍
