### ISSUE TITLE
Filter the posts

### ISSUE THREAD

**Issue by boyfromhell** [andreaselia/laravel-firefly#70]
If I want to apply a filter, let's say which was answered correctly and which was not answered correctly,
what is the best method to use?
I guess I can expand the Discussions model.

```
public function scopeResolved(Builder $builder)
    {
        $builder->with(['posts' => fn ($query) => $query->whereNotNull('corrected_at')])
            ->whereHas(
                'posts',
                fn ($query) =>
                $query->whereNotNull('corrected_at')
            );
    }
```

**Comment by andreaselia** [comment]
I would definitely go the route of expanding the Discussion model, and would have probably done it in a similar way to you have with a scope. Then I'd change the controller to allow the filtering when a filter is selected.
