### ISSUE TITLE
What's next?

### ISSUE THREAD

**Issue by CyberEkklesiaOwner** [andreaselia/laravel-firefly#76]
![Capture](https://user-images.githubusercontent.com/7793925/206609912-ab41e130-4d72-456e-a5c4-fe6802490a43.JPG)

How do I use the system? Is there any documentation other than the Readme?

**Comment by andreaselia** [comment]
No other documentation I'm afraid, but to create a discussion you need to fit create a group which the message states. Are you not able to see a "New Group" button anywhere like on the `/groups` (groups index) route?

**Comment by andreaselia** [comment]
Closing this issue as it's not really a bug and more a question of how you create a group/get started as a user. If you have more questions, feel free to post here and I'll respond.
