### ISSUE TITLE
How to seed the package

### ISSUE THREAD

**Issue by tabraiz961** [AndreasElia/laravel-firefly#81]
I noticed there are factories in the package but not a seeding class. @andreaselia 
Am i missing something ???

**Comment by andreaselia** [comment]
Hi @tabraiz961,

We don't ship the package with a seeder as it's not needed.

In order to create a seeder for the package, you'll want to do something like:

```bash
php artisan make:seeder FireflySeeder
```

And then populate it with the models as you would any other seeder/factory in a Laravel application.
