### ISSUE TITLE
API does not recognize custom middleware

### ISSUE THREAD

**Issue by Shegsdev** [AndreasElia/laravel-firefly#84]
Example API: http:localhost:8000/api/forum/g
Returns:
```
Status - 401
JSON - { Unauthorized }
```

- config/firefly.php

```
'api' => [
...
'namespace' => '\Firefly\Http\Controllers\Api',
'middleware' => 'auth:sanctum'
]
```

**Comment by andreaselia** [comment]
Hi @Shegsdev, sorry for the later than I'd have liked reply.

This is interesting. Something tells me that the middleware may actually not be used from the config 🤔 

@tomirons can you see anything regarding the middleware in the config being used? I see middleware usage in the controller construct methods.

**Comment by Shegsdev** [comment]
Thanks for your response @andreaselia 
The API endpoints are public and I'm trying to make it accessible to only logged in users.

I've tried using policies. I think the issue is in the config file.

**Comment by tomirons** [comment]
@Shegsdev I'm not seeing anything wrong within the code itself. You can try a couple things to resolve this.
1. Wrap the middleware in an array `['auth:sanctum']`
2. Run `php artisan route:list --path=forum -vvv` and see debug the middleware that way.

**Comment by Shegsdev** [comment]
@tomirons Thank you for the tips. Although I still can't get it to work, I'll keep trying other ways.
Thanks for pointing out that there's nothing wrong with the code.

**Comment by tomirons** [comment]
Let us know if the problem persists and we can take a deeper look into it.

**Comment by Shegsdev** [comment]
I found a fix. I had to add API-specific middleware in `config/auth.php`
Thanks guys.

**Comment by andreaselia** [comment]
> I found a fix. I had to add API-specific middleware in `config/auth.php` Thanks guys.

Awesome, glad to hear!
